package loader

import (
	"github.com/ahester57/go-ipfs/plugin"
	pluginipldgit "github.com/ahester57/go-ipfs/plugin/plugins/git"
)

// DO NOT EDIT THIS FILE
// This file is being generated as part of plugin build process
// To change it, modify the plugin/loader/preload.sh

var preloadPlugins = []plugin.Plugin{
	pluginipldgit.Plugins[0],
}
